name: Publish Website
on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Upload to HostGator
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.HOSTGATOR_FTP_SERVER }}
          username: ${{ secrets.HOSTGATOR_FTP_USERNAME }}
          password: ${{ secrets.HOSTGATOR_FTP_PASSWORD }}
          server-dir: /public_html/